# Files will be deleted after this duration in minutes without a password
# set to under 1 to disable uploads without a password
max_time: 5

passwords:
  hunter2:
    max_time: 120

# Allowed file extensions, checked only from filename
allowed_extensions:
  # images
  - png
  - jpg
  - jpeg
  - gif
  - bmp
  - raw

  # audio
  - ogg
  - mp3
  - wav
  - flac
  - aac
  - wma

  # video
  - webm
  - mp4
  - mkv

  # archives
  - zip
  - tar
  - xz
  - 7z
  - rar

  # scripts
  - sh
  - fish
  - bash
  - zsh

  # documents
  - txt
  - pdf
  - csv

  # code
  - cpp
  - h
  - c
  - rs

  # misc
  - gpg
  - srt
  - ass

filename:
  # How long should the generated filename be?
  length: 7

  # What characters should be used in the generated filename?
  characters:
    - a
    - b
    - c
    - d
    - e
    - f
    - A
    - B
    - C
    - D
    - E
    - F
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
