# Files will be deleted after this duration in seconds
max_time: 3600

passwords:
  - hunter2

# Allowed file extensions, checked only from filename
allowed_extensions:
  - png
  - jpg
  - jpeg
  - ogg
  - mp3
  - mp4
  - webm
  - tar
  - xz
  - sh
  - fish
  - bash
  - zsh
  - txt

filename:
  # How long should the generated filename be?
  length: 7

  # What characters should be used in the generated filename?
  characters:
    - a
    - b
    - c
    - d
    - e
    - f
    - A
    - B
    - C
    - D
    - E
    - F
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
